
const generateICS = (contest) => {
  const formatDate = (date) => {
    return date.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
  };

  const startTime = new Date(contest.startTime);
  const endTime = new Date(startTime.getTime() + contest.duration * 1000);
  const now = new Date();

  let description = `Coding Contest: ${contest.name}\\n`;
  if (contest.platform) description += `Platform: ${contest.platform}\\n`;
  if (contest.url) description += `URL: ${contest.url}\\n`;
  
  description += `\\nGenerated by Coding Contest Analytics Platform`;

  const icsString = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Coding Contest Analytics Platform//EN',
    'CALSCALE:GREGORIAN',
    'BEGIN:VEVENT',
    `DTSTAMP:${formatDate(now)}`,
    `UID:${contest._id || contest.id || startTime.getTime()}@codinganalytics.local`,
    `DTSTART:${formatDate(startTime)}`,
    `DTEND:${formatDate(endTime)}`,
    `SUMMARY:${contest.name}`,
    `DESCRIPTION:${description}`,
    'END:VEVENT',
    'END:VCALENDAR'
  ].join('\r\n');

  return icsString;
};

module.exports = { generateICS };
