/**
 * Generates an iCalendar (.ics) string for a contest.
 *
 * @param {Object} contest - The contest object
 * @param {string} contest.name - Title of the contest
 * @param {Date} contest.startTime - Start time of the contest
 * @param {number} contest.duration - Duration in seconds
 * @param {string} contest.url - URL of the contest (optional, for description)
 * @param {string} contest.platform - Platform name (optional)
 * @returns {string} The formatted ICS string
 */
const generateICS = (contest) => {
  // Format dates to ICS standard: YYYYMMDDTHHMMSSZ (UTC)
  const formatDate = (date) => {
    return date.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
  };

  const startTime = new Date(contest.startTime);
  const endTime = new Date(startTime.getTime() + contest.duration * 1000);
  const now = new Date();

  // Create description
  let description = `Coding Contest: ${contest.name}\\n`;
  if (contest.platform) description += `Platform: ${contest.platform}\\n`;
  if (contest.url) description += `URL: ${contest.url}\\n`;
  
  description += `\\nGenerated by Coding Contest Analytics Platform`;

  const icsString = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Coding Contest Analytics Platform//EN',
    'CALSCALE:GREGORIAN',
    'BEGIN:VEVENT',
    `DTSTAMP:${formatDate(now)}`,
    `UID:${contest._id || contest.id || startTime.getTime()}@codinganalytics.local`,
    `DTSTART:${formatDate(startTime)}`,
    `DTEND:${formatDate(endTime)}`,
    `SUMMARY:${contest.name}`,
    `DESCRIPTION:${description}`,
    'END:VEVENT',
    'END:VCALENDAR'
  ].join('\r\n');

  return icsString;
};

module.exports = { generateICS };
