import React from 'react';


const formatGoogleDate = (date) => {
  return date.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
};


export default function CalendarButtons({ contest }) {
  const getGoogleCalendarUrl = () => {
    const startTime = new Date(contest.startTime);
    const endTime = new Date(startTime.getTime() + contest.duration * 1000);
    
    const params = new URLSearchParams({
      action: 'TEMPLATE',
      text: contest.name,
      dates: `${formatGoogleDate(startTime)}/${formatGoogleDate(endTime)}`,
      details: `Platform: ${contest.platform || 'N/A'}\n\nGenerated by Coding Contest Analytics Platform`,
    });

    return `https://calendar.google.com/calendar/render?${params.toString()}`;
  };

  const getIcsDownloadUrl = () => {
    return `/api/calendar/${contest._id}`;
  };

  return (
    <div style={{ display: 'flex', gap: '8px', marginTop: '12px' }}>
      <a 
        href={getGoogleCalendarUrl()} 
        target="_blank" 
        rel="noopener noreferrer"
        className="btn btn--sm btn--outline"
        style={{ flex: 1, textAlign: 'center', borderColor: '#4285F4', color: '#4285F4' }}
        title="Add to Google Calendar"
      >
        🗓️ Google Cal
      </a>
      <a 
        href={getIcsDownloadUrl()} 
        download
        className="btn btn--sm btn--outline"
        style={{ flex: 1, textAlign: 'center' }}
        title="Download .ics file"
      >
        ⬇️ .ics
      </a>
    </div>
  );
}
